//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/MainProject/Scripts/Player/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""cbbf30c5-8586-4b8b-bfb9-cff4ba194cee"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e4c822ff-7eb9-4abb-92bc-ada2965dfd6e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""7ed6e911-5756-4987-b283-649bfd3908a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e8ab404b-7353-44b2-977c-a950a4f6a0d0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""0beccd59-1d49-498e-8c4c-b02b2e465c7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseFire"",
                    ""type"": ""Button"",
                    ""id"": ""40842399-a3c8-45be-83f4-808ede5ade26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""926e4c4e-1e88-4dd0-bd6f-59d70850ff2e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""260a1e52-1c85-40c2-bec4-7d93b63f92ac"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69db8395-2cb4-4eba-9d20-7b1bab218839"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""6a276ac0-ebfb-4d89-a2b7-eb35a699c0fc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6380c103-f2bb-4906-96f0-6779c2594089"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7054019e-e9df-444b-9e5d-4fdf1a551eca"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""508c31ab-882f-493a-bb63-7383c5bfc8ce"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e34049f4-5c31-4778-9fea-3b35886c34f6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f79e151a-c3ff-4da6-92c6-691d7a374105"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Dragon"",
            ""id"": ""fd232105-5c5e-49a2-90c2-281598507e6c"",
            ""actions"": [
                {
                    ""name"": ""MouseLook"",
                    ""type"": ""PassThrough"",
                    ""id"": ""82b77e1d-db84-46c1-a8f7-3fccff1b8695"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f62bc2c5-bc6e-45ea-9ab7-c41522244e95"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMouse"",
                    ""type"": ""Button"",
                    ""id"": ""7b338b22-0c0b-4c4c-9b03-ade02ab3f327"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMouse"",
                    ""type"": ""Button"",
                    ""id"": ""12373067-b917-421e-862b-f30b95fcea84"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireBall"",
                    ""type"": ""Button"",
                    ""id"": ""979be57d-65f6-41d2-8f45-83760c02b05f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireBreath"",
                    ""type"": ""Button"",
                    ""id"": ""a315755f-b58f-4c6d-80fe-8c7c1da4637d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireBomb"",
                    ""type"": ""Button"",
                    ""id"": ""5e45a3a5-92e5-4abd-b29d-b28aba69824c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""577e791a-36fa-4481-a76e-f8cac12d9bb6"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e5151c22-b978-4820-8d69-694c58183b90"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a950c384-a7af-4233-800d-065dc261dfb9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ec0aa6e5-9a79-4b27-9136-8e089516bf09"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9a780978-2a78-4403-a72e-b9e7e71e16c6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1fc6b309-a62f-4d6f-9791-76b8a4307625"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3858a439-c743-493d-9d2c-e0cb85d63331"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4afb143-1604-4ff7-9167-29d37e817314"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed4c6138-8f4c-4b0d-bed2-683e8603e935"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireBall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49cc8f08-17b9-4edb-8e78-0db412965286"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireBall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d177c889-87d4-4a9f-9155-2f6d47ccde6a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireBreath"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53e7d492-280e-4565-a332-148b9aa6dd66"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireBreath"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67641a93-c30f-45f5-b13d-ea3fc8c224e1"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireBomb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a31b2cd5-bced-495a-9e0f-da5e9ae5cb5c"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireBomb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        m_Player_MouseFire = m_Player.FindAction("MouseFire", throwIfNotFound: true);
        // Dragon
        m_Dragon = asset.FindActionMap("Dragon", throwIfNotFound: true);
        m_Dragon_MouseLook = m_Dragon.FindAction("MouseLook", throwIfNotFound: true);
        m_Dragon_Movement = m_Dragon.FindAction("Movement", throwIfNotFound: true);
        m_Dragon_LeftMouse = m_Dragon.FindAction("LeftMouse", throwIfNotFound: true);
        m_Dragon_RightMouse = m_Dragon.FindAction("RightMouse", throwIfNotFound: true);
        m_Dragon_FireBall = m_Dragon.FindAction("FireBall", throwIfNotFound: true);
        m_Dragon_FireBreath = m_Dragon.FindAction("FireBreath", throwIfNotFound: true);
        m_Dragon_FireBomb = m_Dragon.FindAction("FireBomb", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Interact;
    private readonly InputAction m_Player_MouseFire;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputAction @MouseFire => m_Wrapper.m_Player_MouseFire;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Interact.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @MouseFire.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseFire;
                @MouseFire.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseFire;
                @MouseFire.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseFire;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @MouseFire.started += instance.OnMouseFire;
                @MouseFire.performed += instance.OnMouseFire;
                @MouseFire.canceled += instance.OnMouseFire;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Dragon
    private readonly InputActionMap m_Dragon;
    private IDragonActions m_DragonActionsCallbackInterface;
    private readonly InputAction m_Dragon_MouseLook;
    private readonly InputAction m_Dragon_Movement;
    private readonly InputAction m_Dragon_LeftMouse;
    private readonly InputAction m_Dragon_RightMouse;
    private readonly InputAction m_Dragon_FireBall;
    private readonly InputAction m_Dragon_FireBreath;
    private readonly InputAction m_Dragon_FireBomb;
    public struct DragonActions
    {
        private @PlayerControls m_Wrapper;
        public DragonActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseLook => m_Wrapper.m_Dragon_MouseLook;
        public InputAction @Movement => m_Wrapper.m_Dragon_Movement;
        public InputAction @LeftMouse => m_Wrapper.m_Dragon_LeftMouse;
        public InputAction @RightMouse => m_Wrapper.m_Dragon_RightMouse;
        public InputAction @FireBall => m_Wrapper.m_Dragon_FireBall;
        public InputAction @FireBreath => m_Wrapper.m_Dragon_FireBreath;
        public InputAction @FireBomb => m_Wrapper.m_Dragon_FireBomb;
        public InputActionMap Get() { return m_Wrapper.m_Dragon; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DragonActions set) { return set.Get(); }
        public void SetCallbacks(IDragonActions instance)
        {
            if (m_Wrapper.m_DragonActionsCallbackInterface != null)
            {
                @MouseLook.started -= m_Wrapper.m_DragonActionsCallbackInterface.OnMouseLook;
                @MouseLook.performed -= m_Wrapper.m_DragonActionsCallbackInterface.OnMouseLook;
                @MouseLook.canceled -= m_Wrapper.m_DragonActionsCallbackInterface.OnMouseLook;
                @Movement.started -= m_Wrapper.m_DragonActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_DragonActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_DragonActionsCallbackInterface.OnMovement;
                @LeftMouse.started -= m_Wrapper.m_DragonActionsCallbackInterface.OnLeftMouse;
                @LeftMouse.performed -= m_Wrapper.m_DragonActionsCallbackInterface.OnLeftMouse;
                @LeftMouse.canceled -= m_Wrapper.m_DragonActionsCallbackInterface.OnLeftMouse;
                @RightMouse.started -= m_Wrapper.m_DragonActionsCallbackInterface.OnRightMouse;
                @RightMouse.performed -= m_Wrapper.m_DragonActionsCallbackInterface.OnRightMouse;
                @RightMouse.canceled -= m_Wrapper.m_DragonActionsCallbackInterface.OnRightMouse;
                @FireBall.started -= m_Wrapper.m_DragonActionsCallbackInterface.OnFireBall;
                @FireBall.performed -= m_Wrapper.m_DragonActionsCallbackInterface.OnFireBall;
                @FireBall.canceled -= m_Wrapper.m_DragonActionsCallbackInterface.OnFireBall;
                @FireBreath.started -= m_Wrapper.m_DragonActionsCallbackInterface.OnFireBreath;
                @FireBreath.performed -= m_Wrapper.m_DragonActionsCallbackInterface.OnFireBreath;
                @FireBreath.canceled -= m_Wrapper.m_DragonActionsCallbackInterface.OnFireBreath;
                @FireBomb.started -= m_Wrapper.m_DragonActionsCallbackInterface.OnFireBomb;
                @FireBomb.performed -= m_Wrapper.m_DragonActionsCallbackInterface.OnFireBomb;
                @FireBomb.canceled -= m_Wrapper.m_DragonActionsCallbackInterface.OnFireBomb;
            }
            m_Wrapper.m_DragonActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MouseLook.started += instance.OnMouseLook;
                @MouseLook.performed += instance.OnMouseLook;
                @MouseLook.canceled += instance.OnMouseLook;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @LeftMouse.started += instance.OnLeftMouse;
                @LeftMouse.performed += instance.OnLeftMouse;
                @LeftMouse.canceled += instance.OnLeftMouse;
                @RightMouse.started += instance.OnRightMouse;
                @RightMouse.performed += instance.OnRightMouse;
                @RightMouse.canceled += instance.OnRightMouse;
                @FireBall.started += instance.OnFireBall;
                @FireBall.performed += instance.OnFireBall;
                @FireBall.canceled += instance.OnFireBall;
                @FireBreath.started += instance.OnFireBreath;
                @FireBreath.performed += instance.OnFireBreath;
                @FireBreath.canceled += instance.OnFireBreath;
                @FireBomb.started += instance.OnFireBomb;
                @FireBomb.performed += instance.OnFireBomb;
                @FireBomb.canceled += instance.OnFireBomb;
            }
        }
    }
    public DragonActions @Dragon => new DragonActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnMouseFire(InputAction.CallbackContext context);
    }
    public interface IDragonActions
    {
        void OnMouseLook(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnLeftMouse(InputAction.CallbackContext context);
        void OnRightMouse(InputAction.CallbackContext context);
        void OnFireBall(InputAction.CallbackContext context);
        void OnFireBreath(InputAction.CallbackContext context);
        void OnFireBomb(InputAction.CallbackContext context);
    }
}
